// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addwisdom.sql

package database

import (
	"context"
	"database/sql"
)

const addWisdom = `-- name: AddWisdom :one
INSERT INTO wisdoms (data, author)
values (
        $1,
        $2
       )
returning id, data, author
`

type AddWisdomParams struct {
	Data   sql.NullString
	Author string
}

func (q *Queries) AddWisdom(ctx context.Context, arg AddWisdomParams) (Wisdom, error) {
	row := q.db.QueryRowContext(ctx, addWisdom, arg.Data, arg.Author)
	var i Wisdom
	err := row.Scan(&i.ID, &i.Data, &i.Author)
	return i, err
}
