// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Wisdom struct {
	ID     sql.NullInt32
	Data   sql.NullString
	Author string
}
